const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let dashboard,selectedGame;
const logo=t=>t.logo||(t.espn_id?`https://a.espncdn.com/i/teamlogos/ncaa/500/${t.espn_id}.png`:"");
const abbr=t=>t.abbr||t.name.split(/\s+/).map(x=>x[0]).join("").slice(0,4).toUpperCase();
const teamLogo=(t,cls="team-logo")=>logo(t)?`<img class="${cls}" src="${logo(t)}" alt="${esc(t.name)} logo" loading="lazy">`:"";
const color=(t,i)=>t.color||(i===0?"#4aa8ff":"#9a78ff");
const rank=v=>v==null?"—":Math.max(1,Math.min(138,Math.round(1+(100-Number(v))*1.37)));
const val=v=>v==null?"—":(Math.abs(Number(v))<=3?Number(v).toFixed(2):Math.round(Number(v)));
const kickoff=g=>{if(!g.kickoff)return "Kickoff TBD";const d=new Date(g.kickoff);return new Intl.DateTimeFormat("en-US",{weekday:"short",hour:"numeric",minute:"2-digit",timeZone:"America/New_York",timeZoneName:"short"}).format(d)};
const spreadLabel=g=>{const s=Number(g.market?.spread);if(!Number.isFinite(s))return "—";if(s===0)return "PK";const team=s<0?abbr(g.home):abbr(g.away);return `${team} ${s>0?"+":""}${s}`};
const HELP={"Overall Success Rate":"Share of offensive plays graded successful by down and distance.","Defensive Success Rate":"Share of opponent plays graded successful by down and distance; lower raw rates are stronger defense.","Offensive Efficiency":"Opponent-adjusted offensive efficiency relative to the FBS field.","Defensive Efficiency":"Opponent-adjusted defensive efficiency relative to the FBS field.","Passing Success":"Passing-play success relative to the FBS field.","Defensive Passing Success":"Opponent passing success allowed relative to the FBS field.","Rushing Success":"Rushing-play success relative to the FBS field.","Defensive Rushing Success":"Opponent rushing success allowed relative to the FBS field.","Explosiveness":"Ability to generate high-value explosive plays.","Explosiveness Prevention":"Ability to prevent high-value explosive plays.","Finishing Drives":"Offensive performance after creating scoring opportunities.","Defensive Finishing Drives":"Defensive performance after opponents create scoring opportunities.","Third Down Conversion":"Opponent-adjusted offensive third-down performance in standard deviations.","Third Down Defense":"Opponent-adjusted defensive third-down performance in standard deviations.","Red Zone TD Rate":"Opponent-adjusted offensive red-zone touchdown performance in standard deviations.","Red Zone TD Defense":"Opponent-adjusted defensive red-zone touchdown prevention in standard deviations."};
function season(t,i){const f=t.form||{};return `<article class="season-team" style="--team-color:${color(t,i)}"><div class="season-team-head">${teamLogo(t,"season-team-logo")}<b>${esc(abbr(t))}</b></div><div class="season-stats"><span><strong>${esc(t.record||"—")}</strong><small>Record</small></span><span><strong>${f.avg_points??"—"}</strong><small>PPG</small></span><span><strong>${f.avg_allowed??"—"}</strong><small>PPG Allowed</small></span></div></article>`}
function metricCard(m,type){
 const isOff=type==="offense";
 const kicker=isOff?"OFFENSE":"DEFENSE";
 const label=isOff?(m.offense_label||m.label):(m.defense_label||m.label);
 const values=[
   [selectedGame.away,0,isOff?m.away_offense:m.away_defense],
   [selectedGame.home,1,isOff?m.home_offense:m.home_defense]
 ];
 const isSd=["Third Down Conversion","Red Zone TD Rate","Red Zone Points / Trip"].includes(m.label);
 const line=([t,i,v])=>`<div class="metric-team" style="--team-color:${color(t,i)}"><span class="metric-team-name">${teamLogo(t,"metric-logo")}<b>${esc(abbr(t))}</b></span><span class="metric-number">${val(v)}${isSd?" SD":""}</span><span class="metric-rank"><b>${isSd?"—":"#"+rank(v)}</b><small>CFB rank</small></span><span class="metric-track"><i style="width:${isSd?50:Math.max(2,Math.min(100,Number(v)||0))}%"></i></span></div>`;
 return `<article class="metric-card"><div class="metric-title"><span><small class="metric-kicker">${kicker} METRIC</small><span class="metric-name">${esc(label)}<button class="info" aria-label="About ${esc(label)}" data-tip="${esc(HELP[label]||"Opponent-adjusted CFB performance.")}">?</button></span></span><span class="rank-heading"><i>SEASON STAT</i><b>CFB RANK</b></span></div>${values.map(line).join("")}</article>`
}
function pair(m){return metricCard(m,"offense")+metricCard(m,"defense")}
function marketTrendRow(t){
 return `<article class="trend-card"><div class="trend-card-head"><strong>${esc(t.label)}</strong><button class="info" data-tip="${esc(t.note||"Current-season betting result.")}" aria-label="About ${esc(t.label)}">?</button></div><div class="trend-values"><span style="--team-color:${color(selectedGame.away,0)}">${teamLogo(selectedGame.away,"trend-logo")}<b>${esc(t.away)}</b></span><i>VS</i><span style="--team-color:${color(selectedGame.home,1)}">${teamLogo(selectedGame.home,"trend-logo")}<b>${esc(t.home)}</b></span></div></article>`;
}
function marketResults(){
 const rows=selectedGame.market_trends||[];
 if(!rows.length)return"";
 return `<section class="trend-group"><div class="trend-group-title"><span>↗</span><h4>Market Results</h4></div><div class="trend-grid">${rows.map(marketTrendRow).join("")}</div></section>`;
}
const usagePct=v=>v==null?"—":`${Math.round((Number(v)<=1?Number(v)*100:Number(v))*10)/10}%`;
function collegePlayerCard(player,team){
 const items=(player.usage||[]).map(item=>`<div class="usage"><b>${usagePct(item.value)}</b><span>${esc(item.label)}</span></div>`).join("");
 const pos=String(player.position||"").toUpperCase();
 const statLabels=pos==="QB"?["CMP","ATT","PASS YDS","PASS TD","INT","RUSH YDS"]:pos==="RB"?["RUSH","RUSH YDS","RUSH TD","REC","REC YDS","REC TD"]:["REC","REC YDS","REC TD","RUSH","RUSH YDS","RUSH TD"];
 const production=statLabels.map(label=>`<span><b>—</b><small>${label}</small><em>season stats pending</em></span>`).join("");
 const pending=player.placeholder?`<div class="availability-note"><b>Usage data:</b> Player usage will populate on the next successful season refresh.</div>`:"";
 return `<article class="player-card" style="--team-color:${color(team,team===selectedGame.away?0:1)}"><div class="player-top"><div class="player-identity">${teamLogo(team,"player-team-logo")}<div><span class="position">${esc(player.position||"—")} · ${esc(abbr(team))}</span><h3>${esc(player.name||"Usage data pending")}</h3></div></div><span class="subtle">2026 usage</span></div>${pending}<div class="production-line">${production}</div><div class="usage-label"><b>Opportunity share</b><button class="info" data-tip="Season usage share from CFBD, including overall, pass, rush and third-down involvement." aria-label="About opportunity share">?</button></div><div class="usage-grid">${items||'<div class="usage"><b>—</b><span>Pending</span></div>'}</div></article>`;
}
function playerOpportunity(){
 const players=selectedGame.players||[];
 return `<div class="players">${players.map((p,i)=>collegePlayerCard(p,i<4?selectedGame.away:selectedGame.home)).join("")}</div>`;
}
function formSchedule(){
 const fmt=t=>(t.form?.last_five||[]).map(x=>x.result).join(" · ")||"—";
 const travel=t=>(t.form?.last_five||[]).map(x=>(x.location==="A"?"@":"")+x.opponent).join(" · ")||"—";
 const rest=t=>{const games=t.form?.last_five||[];if(!games.length||!selectedGame.week)return"—";const lastWeek=Math.max(...games.map(x=>Number(x.week)||0));const gap=Math.max(0,Number(selectedGame.week)-lastWeek-1);return gap>0?`${gap}-week bye`:"Standard week"};
 const row=(label,a,h,note,seq=false)=>`<article class="context-card${seq?" context-card--sequence":""}"><strong>${label}</strong><div class="context-sides"><span style="--team-color:${color(selectedGame.away,0)}"><small>${esc(abbr(selectedGame.away))}</small><b>${esc(a)}</b></span><i>VS</i><span style="--team-color:${color(selectedGame.home,1)}"><small>${esc(abbr(selectedGame.home))}</small><b>${esc(h)}</b></span></div><p>${note}</p></article>`;
 return `<section class="context-panel"><div class="context-title"><span>◷</span><div><h4>Form & Schedule</h4><p>Recent results, recovery time and travel context at a glance.</p></div></div><div class="context-grid">${row("Last five games",fmt(selectedGame.away),fmt(selectedGame.home),"Last 5 Results",true)}${row("Rest before kickoff",rest(selectedGame.away),rest(selectedGame.home),"Derived from each team's most recent completed game week.")}${row("Travel sequence",travel(selectedGame.away),travel(selectedGame.home),"Last 5 Game Locations",true)}${row("Game setting",selectedGame.context?.neutral_site?"Neutral": "Road",selectedGame.context?.neutral_site?"Neutral":"Home",selectedGame.context?.conference_game?"Conference matchup.":"Non-conference matchup.")}</div></section>`}
function feature(){const f=selectedGame.featured_mismatch;if(!f)return"";const off=f.side?.startsWith("away")?selectedGame.away:selectedGame.home,def=off===selectedGame.away?selectedGame.home:selectedGame.away;const offRank=rank(f.offense_percentile),defRank=rank(f.opponent_defense_percentile);return `<section class="efficiency-feature"><div class="feature-head"><span>◎</span><div><p>FEATURED MATCHUP · LARGEST CFB-RANK GAP</p><h4>${esc(f.metric)}</h4></div></div><div class="feature-values"><span style="--team-color:${color(off,0)}">${teamLogo(off,"trend-logo")}<small>${esc(abbr(off))} · offense · CFB #${offRank}</small><b>${val(f.offense_percentile)}</b></span><i>VS</i><span style="--team-color:${color(def,1)}">${teamLogo(def,"trend-logo")}<small>${esc(abbr(def))} · defense · CFB #${defRank}</small><b>${val(f.opponent_defense_percentile)}</b></span></div><p><b>Why it matters:</b> This is the largest opponent-adjusted unit discrepancy in the matchup. Rank gap: ${Math.abs(offRank-defRank)} places.</p></section>`}
function factors(){const items=(selectedGame.trends||[]).slice(0,8).map(t=>{let title=t.metric||"Game context",detail=t.detail||((t.team||"")+" has the stronger "+(t.metric||"matchup")+" profile.");return `<li><span>${t.type==="matchup_edge"?"↗":"!"}</span><p><small>${esc((t.type||"CONTEXT").replaceAll("_"," "))}</small><b>${esc(title)}</b>${esc(detail)}</p></li>`}).join("");return `<section class="factor-panel"><div class="factor-heading"><div><p class="eyebrow">KEY MATCHUP FACTORS</p><h3>What deserves the closest attention</h3></div><span>Largest matchup discrepancies—not a prediction</span></div><ul>${items}</ul></section>`}
function renderDetail(){
 const g=selectedGame,m=g.market||{},ml=(m.away_moneyline!=null||m.home_moneyline!=null)?`ML ${abbr(g.away)} ${m.away_moneyline??"—"} · ${abbr(g.home)} ${m.home_moneyline??"—"}`:"ML —",markets=[`Spread ${spreadLabel(g)}`,`Total ${m.total??"—"}`,ml,g.weather?.summary||"Weather unavailable"].map(x=>`<span class="pill">${esc(x)}</span>`).join("");
 $("#gameDetail").innerHTML=`<div class="matchup-title"><div><p class="eyebrow">${kickoff(g)}</p><div class="matchup-teams"><span>${teamLogo(g.away)}<b>${esc(g.away.name)}</b></span><i>at</i><span>${teamLogo(g.home)}<b>${esc(g.home.name)}</b></span></div></div><div class="market-strip">${markets}</div></div>
 <section class="season-overview"><p>SEASON SNAPSHOT · COMPLETED GAMES</p><div class="season-overview-grid">${season(g.away,0)}${season(g.home,1)}</div></section>
 <section class="section"><div class="section-head"><div><p class="eyebrow">EFFICIENCY & CFB RANK</p><h3>How the teams compare</h3></div><span class="subtle">#1 = best in FBS</span></div><details class="reading-guide"><summary>How to read these numbers</summary><div><p><b>Stat</b> shows the opponent-adjusted metric value.</p><p><b>CFB Rank</b> translates percentile position across the FBS field.</p><p><b>Each row</b> pairs an offensive metric with its corresponding defensive metric.</p></div></details><div class="metric-columns-head"><span>OFFENSIVE METRICS</span><span>DEFENSIVE METRICS</span></div><div class="grid">${(g.matchup_metrics||[]).map(pair).join("")}</div></section>
 <section class="section">${feature()}</section>
 <section class="section"><div class="section-head"><div><p class="eyebrow">TRENDS & SITUATIONAL CONTEXT</p><h3>The matchup at a glance</h3></div><span class="subtle">Tap ? for definitions</span></div><div class="trend-groups">${marketResults()}${formSchedule()}</div></section>
 <section class="section">${factors()}</section>
 <section class="section"><div class="section-head section-head-solo"><div><p class="eyebrow">PLAYER OPPORTUNITY</p></div></div>${playerOpportunity()}</section>`}
function selectGame(id){selectedGame=dashboard.games.find(g=>String(g.game_id)===String(id));document.querySelectorAll(".game-card").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.id===String(id))));$("#gameDetail").hidden=false;renderDetail()}
function render(){const d=new Date(dashboard.slate.generated_at);$("#updated").textContent="Updated "+d.toLocaleString("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/New_York",timeZoneName:"short"});$("#games").innerHTML=dashboard.games.map(g=>`<button class="game-card" data-id="${g.game_id}" aria-pressed="false"><span class="game-time">${kickoff(g)}</span><span class="teams"><span>${teamLogo(g.away,"rail-logo")}<b>${esc(g.away.name)}</b></span><span>${teamLogo(g.home,"rail-logo")}<b>${esc(g.home.name)}</b></span></span><span class="markets"><span>${esc(spreadLabel(g))}</span><span>O/U ${esc(g.market?.total??"—")}</span></span></button>`).join("");document.querySelectorAll(".game-card").forEach(b=>b.addEventListener("click",()=>selectGame(b.dataset.id)));$("#gameDetail").hidden=true}
document.addEventListener("click",e=>{const b=e.target.closest(".info");if(!b||!window.matchMedia("(max-width:760px)").matches)return;e.preventDefault();let d=document.querySelector(".definition-dialog");if(!d){d=document.createElement("dialog");d.className="definition-dialog";d.innerHTML='<div class="definition-dialog-head"><strong></strong><button type="button">✕</button></div><p></p>';d.querySelector("button").onclick=()=>d.close();document.body.appendChild(d)}d.querySelector("strong").textContent=b.getAttribute("aria-label")?.replace(/^About /,"")||"Definition";d.querySelector("p").textContent=b.dataset.tip||"";d.showModal()});
fetch("data/dashboard.json",{cache:"no-store"}).then(r=>{if(!r.ok)throw Error("Dashboard data unavailable");return r.json()}).then(x=>{dashboard=x;render()}).catch(e=>{$("#updated").textContent=e.message});