const $=x=>document.getElementById(x);let upcoming,selected,market,historical=[];
async function get(u){const r=await fetch(u,{cache:"no-cache"});if(!r.ok)throw Error("Unable to load "+u);return r.json()}
const odds=v=>v==null?"—":(v>0?"+":"")+v,rank=p=>p.ap_rank?"AP #"+p.ap_rank:"AP Unranked";
function line(g){return `<span>${g.spread==null?"Spread unavailable":g.home+" "+(g.spread>0?"+":"")+g.spread}</span><span>${g.home_moneyline==null?"ML unavailable":g.home+" "+odds(g.home_moneyline)}</span><span>${g.over_under==null?"Total unavailable":"O/U "+g.over_under}</span>`}
function gameCard(g,i){return `<button class="game" data-i="${i}"><div class="date">${new Date(g.start_date).toLocaleString([], {weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</div><div class="teams"><b>${g.away}</b><small>${rank(g.away_profile)} · Strength #${g.away_profile.national_strength_rank}</small><i>@</i><b>${g.home}</b><small>${rank(g.home_profile)} · Strength #${g.home_profile.national_strength_rank}</small></div><div class="lines">${line(g)}</div></button>`}
async function init(){try{upcoming=await get("data/upcoming.json");$("status").textContent=upcoming.games.length?`${upcoming.games.length} games available in the next seven days`:"No games are currently scheduled in the next seven days.";$("games").innerHTML=upcoming.games.map(gameCard).join("")}catch(e){$("status").textContent="The upcoming slate is temporarily unavailable.";console.error(e)}}
function dist(a,b){return Math.abs((a??0)-(b??0))}
function features(g,m){const hp=g.home_profile,ap=g.away_profile,base={strengthGap:hp.strength_score-ap.strength_score,homeStrength:hp.strength_score,awayStrength:ap.strength_score,conference:g.conference_game?1:0,neutral:g.neutral_site?1:0,homeLoss:hp.recent_form.coming_off_loss?1:0,awayLoss:ap.recent_form.coming_off_loss?1:0,homeWins:hp.recent_form.wins??0,awayWins:ap.recent_form.wins??0};if(m==="spread")return {...base,line:g.spread};if(m==="total")return {...base,total:g.over_under,homePts:hp.recent_form.avg_points,awayPts:ap.recent_form.avg_points,homeAllow:hp.recent_form.avg_allowed,awayAllow:ap.recent_form.avg_allowed};return base}
function similarity(a,b,m){const A=features(a,m),B=features(b,m);let score=100;const weights=m==="spread"?{line:3,strengthGap:1.6,homeStrength:.35,awayStrength:.35,homeWins:2,awayWins:2,conference:7,neutral:7,homeLoss:5,awayLoss:5}:m==="total"?{total:2.2,homePts:.6,awayPts:.6,homeAllow:.6,awayAllow:.6,strengthGap:.5,conference:5,neutral:5}:{strengthGap:2,homeStrength:.5,awayStrength:.5,homeWins:2,awayWins:2,conference:6,neutral:6,homeLoss:5,awayLoss:5};for(const k in weights){if(A[k]==null||B[k]==null){score-=2;continue}score-=dist(A[k],B[k])*weights[k]}return Math.max(0,Math.round(score))}
function why(g,s){const r=[];if(market==="spread"&&selected.spread!=null&&g.spread!=null&&dist(selected.spread,g.spread)<=2)r.push("Similar point spread");if(market==="total"&&selected.over_under!=null&&g.over_under!=null&&dist(selected.over_under,g.over_under)<=4)r.push("Similar market total");if(selected.conference_game===g.conference_game)r.push(selected.conference_game?"Both conference games":"Both non-conference games");if(dist(selected.home_profile.strength_score,g.home_profile.strength_score)<=8)r.push("Similar home-team strength");if(dist(selected.away_profile.strength_score,g.away_profile.strength_score)<=8)r.push("Similar road-team strength");return r.slice(0,4)}
async function match(m){market=m;$("resultsSection").hidden=false;$("resultTitle").textContent=`${selected.away} at ${selected.home} · ${m==="total"?"O/U Total":m[0].toUpperCase()+m.slice(1)}`;$("matches").innerHTML="Searching verified historical games…";if(!historical.length){historical=(await Promise.all(Array.from({length:12},(_,i)=>get(`data/historical/${2015+i}.json`)))).flatMap(x=>x.games)}const candidates=historical.filter(g=>g.result&&g.game_id!==selected.game_id&&(m!=="spread"||g.spread!=null)&&(m!=="total"||g.over_under!=null)).map(g=>({g,s:similarity(selected,g,m)})).sort((a,b)=>b.s-a.s).slice(0,5);renderMatches(candidates)}
function renderMatches(xs){let hc=0,ac=0,o=0,u=0;for(const {g} of xs){if(g.result.ats==="home_cover")hc++;if(g.result.ats==="away_cover")ac++;if(g.result.total==="over")o++;if(g.result.total==="under")u++}$("summary").innerHTML=`<div><b>${hc}</b><span>Home covers</span></div><div><b>${ac}</b><span>Away covers</span></div><div><b>${o}-${u}</b><span>Over–Under</span></div><div><b>${xs.length}</b><span>Matches</span></div>`;$("matches").innerHTML=xs.map(({g,s},i)=>`<article><div class="matchtop"><span>#${i+1} · ${g.season} Week ${g.week}</span><b>${s}% Match</b></div><h3>${g.away} at ${g.home}</h3><div class="matchlines">${line(g)}</div><ul>${why(g,s).map(x=>"<li>"+x+"</li>").join("")}</ul><div class="outcome">Final: ${g.away} ${g.result.away_points}, ${g.home} ${g.result.home_points} · ${g.result.ats?.replace("_"," ")||"ATS unavailable"} · ${g.result.total||"Total unavailable"}</div></article>`).join("")}
$("games").addEventListener("click",e=>{const b=e.target.closest(".game");if(!b)return;document.querySelectorAll(".game").forEach(x=>x.classList.toggle("selected",x===b));selected=upcoming.games[+b.dataset.i];$("marketSection").hidden=false;$("resultsSection").hidden=true;$("marketSection").scrollIntoView({behavior:"smooth"})});document.querySelector(".markets").addEventListener("click",e=>{const b=e.target.closest("button");if(b)match(b.dataset.market)});init();