let manifest,current,weekData;const $=id=>document.getElementById(id),fmt=v=>v==null?"Unavailable":v;
async function json(url){const r=await fetch(url,{cache:"no-cache"});if(!r.ok)throw Error("Data request failed");return r.json()}
function options(el,vals,label=x=>x){el.innerHTML=vals.map(v=>`<option value="${v}">${label(v)}</option>`).join("")}
async function init(){try{manifest=await json("data/manifest.json");options($("season"),manifest.seasons.map(x=>x.season).reverse());await seasonChanged()}catch(e){$("status").textContent="Verified data is temporarily unavailable.";console.error(e)}}
async function seasonChanged(){const y=$("season").value||$("season").options[0]?.value;current=await json(`data/weekly/${y}.json`);options($("week"),Object.keys(current.weeks).map(Number).sort((a,b)=>a-b),x=>"Week "+x);loadWeek()}
function loadWeek(){weekData=current.weeks[$("week").value];if(!weekData)return;const teams=weekData.ranking;options($("teamA"),teams);options($("teamB"),teams);$("teamB").selectedIndex=Math.min(1,teams.length-1);$("status").textContent=`${teams.length} available FBS teams · pregame Week ${$("week").value} · ${$("season").value}`;render()}
function card(team){const r=weekData.teams[team];if(!r||!r.available)return `<h2>${team}</h2><p>Team Strength unavailable</p>`;return `<p class="eyebrow">NATIONAL STRENGTH #${r.national_strength_rank}</p><h2>${team}</h2><div class="ap">${r.ap_rank?"AP #"+r.ap_rank:"AP Unranked"}</div><div class="strength">${r.strength_score}<small>/100</small></div><div class="tier">${r.strength_tier}</div><div class="metrics"><div class="metric"><span>National Strength Rank</span><b>#${r.national_strength_rank} of ${r.fbs_field_size}</b></div><div class="metric"><span>FBS percentile</span><b>Top ${r.top_percent}%</b></div><div class="metric"><span>Timing</span><b>Pregame safe</b></div></div>`}
function render(){const a=$("teamA").value,b=$("teamB").value;$("cardA").innerHTML=card(a);$("cardB").innerHTML=card(b);const x=weekData.teams[a],y=weekData.teams[b];$("edge").textContent=x?.available&&y?.available?(x.strength_score===y.strength_score?"Both teams had the same Team Strength score.":`${x.strength_score>y.strength_score?a:b} held a ${Math.abs(x.strength_score-y.strength_score)}-point Team Strength advantage before this week.`):"Comparison unavailable";ranking()}
function ranking(){const q=$("search").value.toLowerCase();$("rankingRows").innerHTML=weekData.ranking.filter(t=>t.toLowerCase().includes(q)).map(t=>{const r=weekData.teams[t];return `<tr><td>${r.national_strength_rank?"#"+r.national_strength_rank:"—"}</td><td><b>${t}</b></td><td>${fmt(r.strength_score)}/100</td><td><span class="pill">${fmt(r.strength_tier)}</span></td><td>${r.ap_rank?"#"+r.ap_rank:"Unranked"}</td><td>${r.top_percent?"Top "+r.top_percent+"%":"—"}</td></tr>`}).join("")}
document.addEventListener("click",e=>{if(e.target.matches(".tab")){document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===e.target));const ranks=e.target.dataset.view==="rankings";$("compareView").hidden=ranks;$("rankingsView").hidden=!ranks}})
$("season").addEventListener("change",seasonChanged);$("load").addEventListener("click",loadWeek);$("teamA").addEventListener("change",render);$("teamB").addEventListener("change",render);$("search").addEventListener("input",ranking);init();