let data,selected=0;
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const logo=t=>t.logo||(t.espn_id?"https://a.espncdn.com/i/teamlogos/ncaa/500/"+t.espn_id+".png":"");
const img=(t,cls="logo")=>logo(t)?'<img class="'+cls+'" src="'+logo(t)+'" alt="'+esc(t.name)+' logo" onerror="this.remove()">':'<span class="logo-fallback"></span>';
const show=v=>v===null||v===undefined?"—":esc(v);
function gameButton(g,i){return '<button class="game '+(i===selected?'active':'')+'" data-i="'+i+'"><small>Week '+g.week+'</small><div class="mini">'+img(g.away)+'<b>'+esc(g.away.name)+'</b></div><div class="mini">'+img(g.home)+'<b>'+esc(g.home.name)+'</b></div></button>'}
function team(t){return '<div class="team">'+img(t,"team-logo")+'<h3>'+(t.ap_rank?"#"+t.ap_rank+" ":"")+esc(t.name)+'</h3><div class="rank">#'+show(t.team_strength_rank)+' Team Strength · '+esc(t.record||"—")+'</div><div class="strengths"><span class="pill">Strength '+show(t.team_strength)+'</span><span class="pill">OFF '+show(t.offensive_strength)+' (#'+show(t.offensive_strength_rank)+')</span><span class="pill">DEF '+show(t.defensive_strength)+' (#'+show(t.defensive_strength_rank)+')</span><span class="pill">SOS #'+show(t.sos_rank)+'</span></div></div>'}
function form(t){const f=t.form||{};return '<article class="form-card"><small>FORM & SCHEDULE</small><div class="form-grid"><span><b>'+esc(t.record||"—")+'</b> Record</span><span><b>'+show(f.avg_points)+'</b> PPG</span><span><b>'+show(f.avg_allowed)+'</b> PPG Allowed</span><span><b>'+(f.coming_off_loss===true?"Loss":f.coming_off_loss===false?"Win":"—")+'</b> Last Result</span></div></article>'}
function context(g){const bits=[g.context?.conference_game?"Conference Game":"Non-Conference",g.context?.neutral_site?"Neutral Site":"Home/Road"];if(g.away.ap_rank||g.home.ap_rank)bits.push("Ranked-Team Context");return '<div class="context">'+bits.map(x=>'<span class="pill">'+x+'</span>').join("")+'</div>'}
function detail(){const g=data.games[selected];if(!g){$("#detail").innerHTML="<p>No current FBS matchups available.</p>";return}
const metrics=g.matchup_metrics.map(m=>'<article class="metric"><h4>'+esc(m.label)+'</h4><div class="row"><span>'+esc(g.away.name)+' OFF <b>'+show(m.away_offense)+'</b></span><span>'+esc(g.home.name)+' DEF <b>'+show(m.home_defense)+'</b></span><span>'+esc(g.home.name)+' OFF <b>'+show(m.home_offense)+'</b></span><span>'+esc(g.away.name)+' DEF <b>'+show(m.away_defense)+'</b></span></div></article>').join("");
const f=g.featured_mismatch;
$("#detail").innerHTML='<section class="matchup"><div class="teams">'+team(g.away)+'<b class="vs">AT</b>'+team(g.home)+'</div><div class="market"><span class="pill">Spread '+show(g.market.spread)+'</span><span class="pill">O/U '+show(g.market.total)+'</span><span class="pill">'+esc(g.market.provider||"Market")+'</span></div>'+context(g)+'<div class="forms">'+form(g.away)+form(g.home)+'</div><p class="eyebrow">OFFENSE VS DEFENSE</p><div class="metrics">'+metrics+'</div>'+(f?'<div class="feature"><b>FEATURED MISMATCH · '+esc(f.metric)+'</b><div>'+esc(String(f.side).replaceAll("_"," "))+' · '+show(f.percentile_gap)+' percentile-point gap</div></div>':"")+'</section>'}
fetch("data/dashboard.json").then(r=>r.json()).then(x=>{data=x;$("#updated").textContent="V15 · Week "+(x.slate.week??"—");$("#games").innerHTML=x.games.map(gameButton).join("");$("#games").onclick=e=>{const b=e.target.closest(".game");if(!b)return;selected=+b.dataset.i;$("#games").innerHTML=data.games.map(gameButton).join("");detail()};detail()}).catch(()=>{$("#updated").textContent="Dashboard data unavailable"});